{{- if or (not .Values.jira.sharedHome.backend) (eq .Values.jira.sharedHome.backend "efs") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jira.fullname" . }}-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "100Gi" .Values.jira.sharedHome.size }}
  storageClassName: ""
  volumeName: {{ include "jira.fullname" . }}-efs-pv
{{- end }}
