{{- $dbSecretName := default (printf "%s-db" (include "jira.fullname" .)) .Values.jira.db.passwordSecretName }}
{{- if .Values.jira.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbSecretName }}
type: Opaque
stringData:
  {{ .Values.jira.db.passwordSecretKey }}: {{ .Values.jira.db.password | quote }}
{{- end }}
